-- HomeMind Mobile baseline. MySQL 8.0+, utf8mb4, all DATETIME(3) values are UTC.
-- SqlSugar maps the BIGINT primary keys. Client mutations use UUIDs for retry safety.
CREATE DATABASE IF NOT EXISTS `nexus_mind` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `nexus_mind`;

CREATE TABLE `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT, `display_name` VARCHAR(64) NOT NULL DEFAULT 'HomeMind user', `avatar_url` VARCHAR(512) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'active', `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai', `locale` VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`), CONSTRAINT `ck_users_status` CHECK (`status` IN ('active','disabled','deleted'))
) ENGINE=InnoDB;

-- provider / issuer / subject_kind: wechat/open-platform/unionid, wechat/{appid}/openid,
-- phone/sms/e164, or email/email/email. subject_hash = SHA-256(canonical subject + server pepper).
CREATE TABLE `user_identities` (
  `id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `provider` VARCHAR(32) NOT NULL, `issuer` VARCHAR(128) NOT NULL, `subject_kind` VARCHAR(32) NOT NULL,
  `subject_hash` BINARY(32) NOT NULL, `subject_encrypted` BLOB NULL, `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `verified_at` DATETIME(3) NOT NULL, `last_used_at` DATETIME(3) NULL, `revoked_at` DATETIME(3) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`), UNIQUE KEY `uk_identity_subject` (`provider`,`issuer`,`subject_kind`,`subject_hash`), KEY `idx_identity_user` (`user_id`,`provider`),
  CONSTRAINT `fk_identity_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_identity_provider` CHECK (`provider` IN ('wechat','phone','email'))
) ENGINE=InnoDB;

CREATE TABLE `password_credentials` (
  `user_id` BIGINT NOT NULL, `password_hash` VARCHAR(255) NOT NULL, `password_changed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `failed_attempts` SMALLINT NOT NULL DEFAULT 0, `locked_until` DATETIME(3) NULL,
  PRIMARY KEY (`user_id`), CONSTRAINT `fk_password_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE `auth_devices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `installation_id` CHAR(36) NOT NULL, `platform` VARCHAR(16) NOT NULL,
  `device_name` VARCHAR(128) NULL, `app_version` VARCHAR(32) NULL, `last_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `revoked_at` DATETIME(3) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`), UNIQUE KEY `uk_device_installation` (`user_id`,`installation_id`), CONSTRAINT `fk_device_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE `auth_refresh_tokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `device_id` BIGINT NOT NULL, `family_id` CHAR(36) NOT NULL, `token_hash` BINARY(32) NOT NULL,
  `expires_at` DATETIME(3) NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `last_used_at` DATETIME(3) NULL, `revoked_at` DATETIME(3) NULL, `revoke_reason` VARCHAR(32) NULL, `replaced_by_id` BIGINT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_refresh_hash` (`token_hash`), KEY `idx_refresh_family` (`family_id`,`revoked_at`), KEY `idx_refresh_user` (`user_id`,`revoked_at`),
  CONSTRAINT `fk_refresh_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_refresh_device` FOREIGN KEY (`device_id`) REFERENCES `auth_devices` (`id`), CONSTRAINT `fk_refresh_replacement` FOREIGN KEY (`replaced_by_id`) REFERENCES `auth_refresh_tokens` (`id`)
) ENGINE=InnoDB;
CREATE TABLE `auth_verification_challenges` (
  `id` CHAR(36) NOT NULL, `purpose` VARCHAR(32) NOT NULL, `channel` VARCHAR(16) NOT NULL, `subject_hash` BINARY(32) NOT NULL, `code_hash` BINARY(32) NOT NULL,
  `expires_at` DATETIME(3) NOT NULL, `consumed_at` DATETIME(3) NULL, `attempt_count` SMALLINT NOT NULL DEFAULT 0, `request_ip_hash` BINARY(32) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`), KEY `idx_challenge_lookup` (`subject_hash`,`purpose`,`expires_at`)
) ENGINE=InnoDB;
CREATE TABLE `auth_audit_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NULL, `event_type` VARCHAR(48) NOT NULL, `provider` VARCHAR(32) NULL, `device_id` BIGINT NULL,
  `ip_hash` BINARY(32) NULL, `user_agent_hash` BINARY(32) NULL, `metadata` JSON NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`), KEY `idx_auth_audit_user` (`user_id`,`created_at`), CONSTRAINT `fk_auth_audit_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`), CONSTRAINT `fk_auth_audit_device` FOREIGN KEY (`device_id`) REFERENCES `auth_devices` (`id`)
) ENGINE=InnoDB;
CREATE TABLE `user_consents` (`user_id` BIGINT NOT NULL, `consent_type` VARCHAR(32) NOT NULL, `version` VARCHAR(32) NOT NULL, `accepted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`user_id`,`consent_type`,`version`), CONSTRAINT `fk_consent_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE `sync_clients` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `installation_id` CHAR(36) NOT NULL, `platform` VARCHAR(16) NOT NULL, `last_pulled_version` BIGINT NOT NULL DEFAULT 0, `last_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_sync_client` (`user_id`,`installation_id`), CONSTRAINT `fk_sync_client_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE `sync_mutations` (`client_id` BIGINT NOT NULL, `mutation_id` CHAR(36) NOT NULL, `applied_version` BIGINT NOT NULL, `received_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`client_id`,`mutation_id`), CONSTRAINT `fk_mutation_client` FOREIGN KEY (`client_id`) REFERENCES `sync_clients` (`id`)) ENGINE=InnoDB;
CREATE TABLE `sync_change_log` (`sync_version` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `entity_type` VARCHAR(40) NOT NULL, `entity_id` BIGINT NOT NULL, `operation` VARCHAR(8) NOT NULL, `changed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`sync_version`), KEY `idx_change_user_cursor` (`user_id`,`sync_version`), CONSTRAINT `fk_change_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `ck_change_operation` CHECK (`operation` IN ('upsert','delete'))) ENGINE=InnoDB;

CREATE TABLE `todo_lists` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `name` VARCHAR(80) NOT NULL, `color` VARCHAR(16) NULL, `sort_order` INT NOT NULL DEFAULT 0, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), CONSTRAINT `fk_list_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE `todos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `list_id` BIGINT NULL, `parent_id` BIGINT NULL, `seq` INT NOT NULL DEFAULT 0,
  `title` VARCHAR(255) NOT NULL, `description` TEXT NULL, `type` VARCHAR(32) NULL, `priority` VARCHAR(16) NULL, `color` VARCHAR(16) NULL, `status` VARCHAR(16) NOT NULL DEFAULT 'pending',
  `due_at` DATETIME(3) NULL, `remind_at` DATETIME(3) NULL, `completed_at` DATETIME(3) NULL, `pinned` TINYINT(1) NOT NULL DEFAULT 0, `sort_order` INT NOT NULL DEFAULT 0,
  `repeat_rule` VARCHAR(512) NULL, `recurrence_anchor_at` DATETIME(3) NULL, `recurrence_parent_id` BIGINT NULL, `report_ignored` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), KEY `idx_todo_user_due` (`user_id`,`status`,`due_at`), KEY `idx_todo_user_updated` (`user_id`,`updated_at`),
  CONSTRAINT `fk_todo_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_todo_list` FOREIGN KEY (`list_id`) REFERENCES `todo_lists` (`id`), CONSTRAINT `fk_todo_parent` FOREIGN KEY (`parent_id`) REFERENCES `todos` (`id`), CONSTRAINT `fk_todo_repeat_parent` FOREIGN KEY (`recurrence_parent_id`) REFERENCES `todos` (`id`)
) ENGINE=InnoDB;
CREATE TABLE `subtasks` (`id` BIGINT NOT NULL AUTO_INCREMENT, `todo_id` BIGINT NOT NULL, `text` VARCHAR(255) NOT NULL, `done` TINYINT(1) NOT NULL DEFAULT 0, `seq` INT NOT NULL DEFAULT 0, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), KEY `idx_subtask_todo` (`todo_id`,`seq`), CONSTRAINT `fk_subtask_todo` FOREIGN KEY (`todo_id`) REFERENCES `todos` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE `todo_tags` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `name` VARCHAR(64) NOT NULL, `color` VARCHAR(16) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE KEY `uk_tag_name` (`user_id`,`name`), CONSTRAINT `fk_tag_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE `todo_tag_links` (`todo_id` BIGINT NOT NULL, `tag_id` BIGINT NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`todo_id`,`tag_id`), CONSTRAINT `fk_tag_link_todo` FOREIGN KEY (`todo_id`) REFERENCES `todos` (`id`), CONSTRAINT `fk_tag_link_tag` FOREIGN KEY (`tag_id`) REFERENCES `todo_tags` (`id`)) ENGINE=InnoDB;
CREATE TABLE `attachments` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `todo_id` BIGINT NULL, `name` VARCHAR(255) NOT NULL, `mime` VARCHAR(127) NOT NULL, `size_bytes` BIGINT NOT NULL, `storage_path` VARCHAR(512) NOT NULL, `content_sha256` BINARY(32) NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE KEY `uk_attachment_path` (`storage_path`), KEY `idx_attachment_user` (`user_id`,`created_at`), CONSTRAINT `fk_attachment_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_attachment_todo` FOREIGN KEY (`todo_id`) REFERENCES `todos` (`id`)) ENGINE=InnoDB;

CREATE TABLE `calendar_events` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `title` VARCHAR(255) NOT NULL, `description` TEXT NULL, `location` VARCHAR(255) NULL, `start_at` DATETIME(3) NOT NULL, `end_at` DATETIME(3) NULL, `timezone` VARCHAR(64) NULL, `all_day` TINYINT(1) NOT NULL DEFAULT 0, `color` VARCHAR(16) NULL, `opacity` DECIMAL(3,2) NULL, `repeat_rule` VARCHAR(1024) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), KEY `idx_event_user_start` (`user_id`,`start_at`), CONSTRAINT `fk_event_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `ck_event_opacity` CHECK (`opacity` IS NULL OR `opacity` BETWEEN 0 AND 1)) ENGINE=InnoDB;
CREATE TABLE `calendar_event_exceptions` (`id` BIGINT NOT NULL AUTO_INCREMENT, `event_id` BIGINT NOT NULL, `original_start_at` DATETIME(3) NOT NULL, `override_title` VARCHAR(255) NULL, `override_start_at` DATETIME(3) NULL, `override_end_at` DATETIME(3) NULL, `is_cancelled` TINYINT(1) NOT NULL DEFAULT 0, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE KEY `uk_event_exception` (`event_id`,`original_start_at`), CONSTRAINT `fk_exception_event` FOREIGN KEY (`event_id`) REFERENCES `calendar_events` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE `calendar_subscriptions` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `name` VARCHAR(128) NOT NULL, `source_url_encrypted` BLOB NOT NULL, `source_url_hash` BINARY(32) NOT NULL, `enabled` TINYINT(1) NOT NULL DEFAULT 1, `refresh_interval_min` INT NOT NULL DEFAULT 60, `last_fetch_at` DATETIME(3) NULL, `last_error` VARCHAR(512) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE KEY `uk_subscription_url` (`user_id`,`source_url_hash`), CONSTRAINT `fk_subscription_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `ck_subscription_interval` CHECK (`refresh_interval_min` BETWEEN 15 AND 1440)) ENGINE=InnoDB;
CREATE TABLE `ical_overrides` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `subscription_id` BIGINT NOT NULL, `source_event_uid` VARCHAR(255) NOT NULL, `recurrence_id` VARCHAR(255) NOT NULL DEFAULT '', `action` VARCHAR(16) NOT NULL, `patch` JSON NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE KEY `uk_ical_override` (`subscription_id`,`source_event_uid`,`recurrence_id`), CONSTRAINT `fk_ical_override_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_ical_override_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `calendar_subscriptions` (`id`) ON DELETE CASCADE, CONSTRAINT `ck_ical_action` CHECK (`action` IN ('rename','hide','reschedule'))) ENGINE=InnoDB;

CREATE TABLE `ai_skills` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `name` VARCHAR(128) NOT NULL, `prompt` TEXT NOT NULL, `scopes` JSON NOT NULL, `is_builtin` TINYINT(1) NOT NULL DEFAULT 0, `is_active` TINYINT(1) NOT NULL DEFAULT 1, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`id`), KEY `idx_skill_user` (`user_id`), CONSTRAINT `fk_skill_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE `ai_configs` (`user_id` BIGINT NOT NULL, `endpoint` VARCHAR(512) NOT NULL, `api_key_encrypted` BLOB NOT NULL, `model` VARCHAR(128) NOT NULL, `temperature` DECIMAL(3,2) NOT NULL DEFAULT 0.70, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`user_id`), CONSTRAINT `fk_aicfg_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `ck_aicfg_temperature` CHECK (`temperature` BETWEEN 0 AND 2)) ENGINE=InnoDB;
CREATE TABLE `ai_call_logs` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `scope` VARCHAR(32) NOT NULL, `skill_id` BIGINT NULL, `model` VARCHAR(128) NULL, `prompt_tokens` INT NULL, `completion_tokens` INT NULL, `latency_ms` INT NULL, `status` VARCHAR(16) NOT NULL, `error_msg` VARCHAR(512) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `idx_ailog_user_time` (`user_id`,`created_at`), CONSTRAINT `fk_ailog_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_ailog_skill` FOREIGN KEY (`skill_id`) REFERENCES `ai_skills` (`id`)) ENGINE=InnoDB;
CREATE TABLE `user_settings` (`user_id` BIGINT NOT NULL, `k` VARCHAR(64) NOT NULL, `v` JSON NOT NULL, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) NULL, `sync_version` BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (`user_id`,`k`), CONSTRAINT `fk_setting_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE `push_subscriptions` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT NOT NULL, `device_id` BIGINT NOT NULL, `endpoint_encrypted` BLOB NOT NULL, `endpoint_hash` BINARY(32) NOT NULL, `p256dh_encrypted` BLOB NOT NULL, `auth_encrypted` BLOB NOT NULL, `expires_at` DATETIME(3) NULL, `last_success_at` DATETIME(3) NULL, `failure_count` SMALLINT NOT NULL DEFAULT 0, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_push_endpoint` (`endpoint_hash`), CONSTRAINT `fk_push_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_push_device` FOREIGN KEY (`device_id`) REFERENCES `auth_devices` (`id`) ON DELETE CASCADE) ENGINE=InnoDB;
