-- Apply after 013_expert_files_and_team_orchestration.mysql.sql.
-- V2.2 family and steward data baseline. All home_id values are JWT tenant IDs.
USE `nexus_mind`;

CREATE TABLE `family_members` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `home_id` BIGINT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `relation` VARCHAR(64) NOT NULL,
  `birthday` DATE NULL,
  `is_elderly` TINYINT(1) NOT NULL DEFAULT 0,
  `is_child` TINYINT(1) NOT NULL DEFAULT 0,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `member_status` VARCHAR(24) NOT NULL DEFAULT 'active',
  `preferences_json` JSON NULL,
  `created_by_user_id` BIGINT NOT NULL,
  `terminal_corrected_by_user_id` BIGINT NULL,
  `terminal_correction_reason` VARCHAR(512) NULL,
  `terminal_corrected_at` DATETIME(3) NULL,
  `deleted_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `row_version` BIGINT NOT NULL DEFAULT 1,
  `sync_version` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_family_member_home_id_id` (`home_id`,`id`),
  KEY `idx_family_member_home_status` (`home_id`,`member_status`,`updated_at`),
  CONSTRAINT `fk_family_member_home` FOREIGN KEY (`home_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `fk_family_member_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_family_member_terminal_corrected_by` FOREIGN KEY (`terminal_corrected_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `ck_family_member_status` CHECK (`member_status` IN ('active','away','permanently_left','deceased')),
  CONSTRAINT `ck_family_member_terminal_correction` CHECK ((`terminal_corrected_at` IS NULL AND `terminal_corrected_by_user_id` IS NULL AND `terminal_correction_reason` IS NULL) OR (`terminal_corrected_at` IS NOT NULL AND `terminal_corrected_by_user_id` IS NOT NULL AND `terminal_correction_reason` IS NOT NULL))
) ENGINE=InnoDB;

CREATE TABLE `family_knowledge` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `home_id` BIGINT NOT NULL,
  `category` VARCHAR(32) NOT NULL,
  `knowledge_key` VARCHAR(256) NOT NULL,
  `knowledge_value` TEXT NOT NULL,
  `notes` TEXT NULL,
  `source_type` VARCHAR(16) NOT NULL DEFAULT 'member',
  `source_member_id` BIGINT NULL,
  `confidence_score` DECIMAL(4,3) NOT NULL,
  `conflict_resolution_strategy` VARCHAR(16) NOT NULL DEFAULT 'latest',
  `resolution_summary` VARCHAR(1024) NULL,
  `created_by_user_id` BIGINT NULL,
  `deleted_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `row_version` BIGINT NOT NULL DEFAULT 1,
  `sync_version` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_family_knowledge_home_key` (`home_id`,`category`,`knowledge_key`,`updated_at`),
  KEY `idx_family_knowledge_source` (`home_id`,`source_member_id`),
  CONSTRAINT `fk_family_knowledge_home` FOREIGN KEY (`home_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `fk_family_knowledge_source_member` FOREIGN KEY (`home_id`,`source_member_id`) REFERENCES `family_members` (`home_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_family_knowledge_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_family_knowledge_category` CHECK (`category` IN ('property','wifi','repair','cleaning','insurance','other')),
  CONSTRAINT `ck_family_knowledge_source` CHECK ((`source_type` = 'member' AND `source_member_id` IS NOT NULL) OR (`source_type` = 'system_ai' AND `source_member_id` IS NULL)),
  CONSTRAINT `ck_family_knowledge_confidence` CHECK (`confidence_score` >= 0 AND `confidence_score` <= 1),
  CONSTRAINT `ck_family_knowledge_strategy` CHECK (`conflict_resolution_strategy` IN ('latest','authority','majority'))
) ENGINE=InnoDB;

CREATE TABLE `decision_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `home_id` BIGINT NOT NULL,
  `scenario` VARCHAR(128) NOT NULL,
  `decision_made` TEXT NOT NULL,
  `rationale` TEXT NULL,
  `alternatives_json` JSON NULL,
  `made_by_member_id` BIGINT NULL,
  `made_by_user_id` BIGINT NULL,
  `decided_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `row_version` BIGINT NOT NULL DEFAULT 1,
  `sync_version` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_decision_history_home_decided` (`home_id`,`decided_at`),
  CONSTRAINT `fk_decision_history_home` FOREIGN KEY (`home_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `fk_decision_history_member` FOREIGN KEY (`home_id`,`made_by_member_id`) REFERENCES `family_members` (`home_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_decision_history_user` FOREIGN KEY (`made_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE `steward_activities` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `home_id` BIGINT NOT NULL,
  `run_id` BIGINT NULL,
  `category` VARCHAR(16) NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `description` TEXT NULL,
  `risk_level` VARCHAR(2) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'pending',
  `result_summary` TEXT NULL,
  `undoable` TINYINT(1) NOT NULL DEFAULT 0,
  `undone_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `row_version` BIGINT NOT NULL DEFAULT 1,
  `sync_version` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_steward_activity_home_status` (`home_id`,`status`,`updated_at`),
  KEY `idx_steward_activity_run` (`run_id`),
  CONSTRAINT `fk_steward_activity_home` FOREIGN KEY (`home_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `fk_steward_activity_run` FOREIGN KEY (`run_id`) REFERENCES `expert_runs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_steward_activity_category` CHECK (`category` IN ('sensing','planning','executing','reporting')),
  CONSTRAINT `ck_steward_activity_risk` CHECK (`risk_level` IN ('L1','L2','L3')),
  CONSTRAINT `ck_steward_activity_status` CHECK (`status` IN ('pending','confirmed','executing','completed','failed','cancelled'))
) ENGINE=InnoDB;

CREATE TABLE `confirmation_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `home_id` BIGINT NOT NULL,
  `activity_id` BIGINT NULL,
  `risk_level` VARCHAR(2) NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `description` TEXT NULL,
  `impact_summary` VARCHAR(1024) NULL,
  `suggested_action` VARCHAR(1024) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'pending',
  `expires_at` DATETIME(3) NULL,
  `confirmed_by_user_id` BIGINT NULL,
  `confirmed_at` DATETIME(3) NULL,
  `denied_by_user_id` BIGINT NULL,
  `denied_at` DATETIME(3) NULL,
  `denial_reason` VARCHAR(512) NULL,
  `expired_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `row_version` BIGINT NOT NULL DEFAULT 1,
  `sync_version` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_confirmation_item_home_pending` (`home_id`,`status`,`risk_level`,`expires_at`),
  KEY `idx_confirmation_item_activity` (`activity_id`),
  CONSTRAINT `fk_confirmation_item_home` FOREIGN KEY (`home_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `fk_confirmation_item_activity` FOREIGN KEY (`activity_id`) REFERENCES `steward_activities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_confirmation_item_confirmed_by` FOREIGN KEY (`confirmed_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_confirmation_item_denied_by` FOREIGN KEY (`denied_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_confirmation_item_risk` CHECK (`risk_level` IN ('L1','L2','L3')),
  CONSTRAINT `ck_confirmation_item_status` CHECK (`status` IN ('pending','confirmed','denied','expired','cancelled')),
  CONSTRAINT `ck_confirmation_item_confirmation` CHECK ((`confirmed_at` IS NULL AND `confirmed_by_user_id` IS NULL) OR (`confirmed_at` IS NOT NULL AND `confirmed_by_user_id` IS NOT NULL)),
  CONSTRAINT `ck_confirmation_item_denial` CHECK ((`denied_at` IS NULL AND `denied_by_user_id` IS NULL AND `denial_reason` IS NULL) OR (`denied_at` IS NOT NULL AND `denied_by_user_id` IS NOT NULL))
) ENGINE=InnoDB;

ALTER TABLE `smart_home_devices`
  ADD COLUMN `zigbee_role` VARCHAR(16) NULL AFTER `online_status`,
  ADD COLUMN `battery_level` TINYINT UNSIGNED NULL AFTER `zigbee_role`,
  ADD COLUMN `signal_lqi` SMALLINT UNSIGNED NULL AFTER `battery_level`,
  ADD COLUMN `health_status` VARCHAR(16) NOT NULL DEFAULT 'healthy' AFTER `signal_lqi`,
  ADD KEY `idx_smart_home_device_health` (`tenant_id`,`health_status`,`updated_at`),
  ADD CONSTRAINT `ck_smart_home_device_zigbee_role` CHECK (`zigbee_role` IS NULL OR `zigbee_role` IN ('end_device','router','coordinator')),
  ADD CONSTRAINT `ck_smart_home_device_battery` CHECK (`battery_level` IS NULL OR `battery_level` <= 100),
  ADD CONSTRAINT `ck_smart_home_device_health` CHECK (`health_status` IN ('healthy','degraded','offline','low_battery'));

ALTER TABLE `expert_runs`
  ADD COLUMN `mode` VARCHAR(16) NOT NULL DEFAULT 'single' AFTER `status`,
  ADD COLUMN `auto_confirm_policy` VARCHAR(16) NOT NULL DEFAULT 'never' AFTER `mode`,
  ADD CONSTRAINT `ck_expert_run_mode` CHECK (`mode` IN ('single','steward')),
  ADD CONSTRAINT `ck_expert_run_auto_confirm_policy` CHECK (`auto_confirm_policy` IN ('L3_only','L2_and_above','never'));
