// <auto-generated />
using System;
using HomeMind.Common.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeMind.Api.Migrations
{
    [DbContext(typeof(HomeMindDbContext))]
    [Migration("20260806021643_AddAiConfigEnabled")]
    partial class AddAiConfigEnabled
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HomeMind.Common.Model.Entities.AccessTokenRevocation", b =>
                {
                    b.Property<string>("TokenId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("expires_at");

                    b.Property<string>("RevokeReason")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("revoked_at");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.ToTable("auth_access_token_revocations");
                });

            modelBuilder.Entity("HomeMind.Common.Model.Entities.AiConfig", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("ApiKeyEncrypted")
                        .HasColumnType("blob")
                        .HasColumnName("api_key_encrypted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Endpoint")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("endpoint");

                    b.Property<string>("Model")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("model");

                    b.Property<long>("SyncVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("sync_version");

                    b.Property<double>("Temperature")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("ai_configs");
                });
        }
    }
}
