using HomeMind.Common.Model.Entities;
using HomeMind.Common.Model.Entities.Family;
using HomeMind.Common.Model.Entities.Life;
using HomeMind.Common.Model.Entities.Memory;
using HomeMind.Common.Model.Entities.SmartHome;
using HomeMind.Common.Model.Entities.Steward;
using Microsoft.EntityFrameworkCore;

namespace HomeMind.Common.Repository;

/// <summary>HomeMind 数据库上下文，集中定义所有物理表与实体的对应关系。</summary>
public sealed class HomeMindDbContext : DbContext
{
    public HomeMindDbContext(DbContextOptions<HomeMindDbContext> options) : base(options) { }

    public DbSet<User> Users => Set<User>();
    public DbSet<UserIdentity> UserIdentities => Set<UserIdentity>();
    public DbSet<PasswordCredential> PasswordCredentials => Set<PasswordCredential>();
    public DbSet<AuthDevice> AuthDevices => Set<AuthDevice>();
    public DbSet<AuthRefreshToken> AuthRefreshTokens => Set<AuthRefreshToken>();
    public DbSet<Tenant> Tenants => Set<Tenant>();
    public DbSet<TenantMember> TenantMembers => Set<TenantMember>();
    public DbSet<TenantMemberInvitation> TenantMemberInvitations => Set<TenantMemberInvitation>();
    public DbSet<WebNavigationPreference> WebNavigationPreferences => Set<WebNavigationPreference>();
    public DbSet<AccessTokenRevocation> AccessTokenRevocations => Set<AccessTokenRevocation>();
    public DbSet<AuthVerificationChallenge> AuthVerificationChallenges => Set<AuthVerificationChallenge>();
    public DbSet<AuthAuditLog> AuthAuditLogs => Set<AuthAuditLog>();
    public DbSet<SyncClient> SyncClients => Set<SyncClient>();
    public DbSet<SyncMutation> SyncMutations => Set<SyncMutation>();
    public DbSet<SyncChangeLog> SyncChangeLogs => Set<SyncChangeLog>();
    public DbSet<UserConsent> UserConsents => Set<UserConsent>();
    public DbSet<Todo> Todos => Set<Todo>();
    public DbSet<Subtask> Subtasks => Set<Subtask>();
    public DbSet<TodoList> TodoLists => Set<TodoList>();
    public DbSet<TodoTag> TodoTags => Set<TodoTag>();
    public DbSet<TodoTagLink> TodoTagLinks => Set<TodoTagLink>();
    public DbSet<Attachment> Attachments => Set<Attachment>();
    public DbSet<CalendarEvent> CalendarEvents => Set<CalendarEvent>();
    public DbSet<CalendarSubscription> CalendarSubscriptions => Set<CalendarSubscription>();
    public DbSet<CalendarEventException> CalendarEventExceptions => Set<CalendarEventException>();
    public DbSet<IcalOverride> IcalOverrides => Set<IcalOverride>();
    public DbSet<AiSkill> AiSkills => Set<AiSkill>();
    public DbSet<SkillCatalog> SkillCatalogs => Set<SkillCatalog>();
    public DbSet<ClippingMaterial> ClippingMaterials => Set<ClippingMaterial>();
    public DbSet<ClippingTask> ClippingTasks => Set<ClippingTask>();
    public DbSet<KnowledgeItem> KnowledgeItems => Set<KnowledgeItem>();
    public DbSet<AiConfig> AiConfigs => Set<AiConfig>();
    public DbSet<AiCallLog> AiCallLogs => Set<AiCallLog>();
    public DbSet<UserSetting> UserSettings => Set<UserSetting>();
    public DbSet<PushSubscription> PushSubscriptions => Set<PushSubscription>();
    public DbSet<Plan> Plans => Set<Plan>();
    public DbSet<PlanItem> PlanItems => Set<PlanItem>();
    public DbSet<Expert> Experts => Set<Expert>();
    public DbSet<ExpertVersion> ExpertVersions => Set<ExpertVersion>();
    public DbSet<ExpertGroup> ExpertGroups => Set<ExpertGroup>();
    public DbSet<ExpertGroupVersion> ExpertGroupVersions => Set<ExpertGroupVersion>();
    public DbSet<ExpertGroupMember> ExpertGroupMembers => Set<ExpertGroupMember>();
    public DbSet<UserExpertPreference> UserExpertPreferences => Set<UserExpertPreference>();
    public DbSet<AgentRun> AgentRuns => Set<AgentRun>();
    public DbSet<ExpertRunContext> ExpertRunContexts => Set<ExpertRunContext>();
    public DbSet<RunStep> RunSteps => Set<RunStep>();
    public DbSet<RunStepDependency> RunStepDependencies => Set<RunStepDependency>();
    public DbSet<ExpertJob> ExpertJobs => Set<ExpertJob>();
    public DbSet<RunEvent> RunEvents => Set<RunEvent>();
    public DbSet<RunArtifact> RunArtifacts => Set<RunArtifact>();
    public DbSet<RunStepUsage> RunStepUsages => Set<RunStepUsage>();
    public DbSet<CreditLedgerEntry> CreditLedgerEntries => Set<CreditLedgerEntry>();
    public DbSet<ExpertRunAction> ExpertRunActions => Set<ExpertRunAction>();
    public DbSet<ActionExecutionAudit> ActionExecutionAudits => Set<ActionExecutionAudit>();
    public DbSet<ConnectorProvider> ConnectorProviders => Set<ConnectorProvider>();
    public DbSet<WorkspaceConnector> WorkspaceConnectors => Set<WorkspaceConnector>();
    public DbSet<ConnectorAuthorizationSession> ConnectorAuthorizationSessions => Set<ConnectorAuthorizationSession>();
    public DbSet<UserConnectorAuthorization> UserConnectorAuthorizations => Set<UserConnectorAuthorization>();
    public DbSet<SmartHomeSpace> SmartHomeSpaces => Set<SmartHomeSpace>();
    public DbSet<SmartHomeDevice> SmartHomeDevices => Set<SmartHomeDevice>();
    public DbSet<DeviceCapability> DeviceCapabilities => Set<DeviceCapability>();
    public DbSet<DeviceState> DeviceStates => Set<DeviceState>();
    public DbSet<Scene> Scenes => Set<Scene>();
    public DbSet<SceneAction> SceneActions => Set<SceneAction>();
    public DbSet<ScenarioTemplate> ScenarioTemplates => Set<ScenarioTemplate>();
    public DbSet<ScenarioInstance> ScenarioInstances => Set<ScenarioInstance>();
    public DbSet<AutomationRule> AutomationRules => Set<AutomationRule>();
    public DbSet<ConnectorSyncJob> ConnectorSyncJobs => Set<ConnectorSyncJob>();
    public DbSet<ExpertFile> ExpertFiles => Set<ExpertFile>();
    public DbSet<ExpertFileObject> ExpertFileObjects => Set<ExpertFileObject>();
    public DbSet<ExpertFileAttachment> ExpertFileAttachments => Set<ExpertFileAttachment>();
    public DbSet<TeamRunTemplate> TeamRunTemplates => Set<TeamRunTemplate>();
    public DbSet<TeamRunTemplateVersion> TeamRunTemplateVersions => Set<TeamRunTemplateVersion>();
    public DbSet<TeamRun> TeamRuns => Set<TeamRun>();
    public DbSet<TeamRunMember> TeamRunMembers => Set<TeamRunMember>();
    public DbSet<TeamRunAudit> TeamRunAudits => Set<TeamRunAudit>();
    public DbSet<FamilyMember> FamilyMembers => Set<FamilyMember>();
    public DbSet<FamilyKnowledge> FamilyKnowledge => Set<FamilyKnowledge>();
    public DbSet<DecisionHistory> DecisionHistory => Set<DecisionHistory>();
    public DbSet<FamilyAuditLog> FamilyAuditLogs => Set<FamilyAuditLog>();
    public DbSet<StewardActivity> StewardActivities => Set<StewardActivity>();
    public DbSet<ConfirmationItem> ConfirmationItems => Set<ConfirmationItem>();
    public DbSet<ConfirmationBatchRecord> ConfirmationBatchRecords => Set<ConfirmationBatchRecord>();
    public DbSet<PersonalFavorite> PersonalFavorites => Set<PersonalFavorite>();
    public DbSet<MemoryCandidate> MemoryCandidates => Set<MemoryCandidate>();
    public DbSet<MemoryReviewReceipt> MemoryReviewReceipts => Set<MemoryReviewReceipt>();
    public DbSet<PersonalMemoryPreference> PersonalMemoryPreferences => Set<PersonalMemoryPreference>();
    public DbSet<LearningMemoryRecord> LearningMemoryRecords => Set<LearningMemoryRecord>();
    public DbSet<TravelAttraction> TravelAttractions => Set<TravelAttraction>();
    public DbSet<Conversation> Conversations => Set<Conversation>();
    public DbSet<ConversationMessage> ConversationMessages => Set<ConversationMessage>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<TenantMember>().HasKey(x => new { x.TenantId, x.UserId });
        modelBuilder.Entity<SyncMutation>().HasKey(x => new { x.ClientId, x.MutationId });
        modelBuilder.Entity<TodoTagLink>().HasKey(x => new { x.TodoId, x.TagId });
        modelBuilder.Entity<UserSetting>().HasKey(x => new { x.UserId, x.Key });
        modelBuilder.Entity<UserConsent>().HasKey(x => new { x.UserId, x.ConsentType, x.Version });
        modelBuilder.Entity<ExpertGroupMember>().HasKey(x => new { x.GroupVersionId, x.ExpertVersionId });
        modelBuilder.Entity<UserExpertPreference>().HasKey(x => new { x.TenantId, x.UserId, x.ExpertId });
        modelBuilder.Entity<RunStepDependency>().HasKey(x => new { x.StepId, x.DependsOnStepId });

        ConfigureStoreGeneratedTimestamps(modelBuilder);

        // MySQL JSON 字段按字符串承载，避免将原始 JSON 再次序列化为字符串。
        modelBuilder.Entity<AiSkill>().Property(x => x.Scopes).HasColumnType("json");
        modelBuilder.Entity<Expert>().Property(x => x.PrivacyScope).HasColumnType("json");
        modelBuilder.Entity<ExpertVersion>().Property(x => x.ToolPolicy).HasColumnType("json");
        modelBuilder.Entity<ExpertVersion>().Property(x => x.OutputSchema).HasColumnType("json");
        modelBuilder.Entity<ExpertGroupVersion>().Property(x => x.OrchestrationPolicy).HasColumnType("json");
        modelBuilder.Entity<ExpertGroupVersion>().Property(x => x.OutputSchema).HasColumnType("json");
        modelBuilder.Entity<AgentRun>().Property(x => x.Input).HasColumnType("json");
        modelBuilder.Entity<AgentRun>().Property(x => x.Result).HasColumnType("json");
        modelBuilder.Entity<AgentRun>().Property(x => x.PermissionSnapshot).HasColumnType("json");
        modelBuilder.Entity<WorkspaceConnector>().Property(x => x.Config).HasColumnType("json");
        modelBuilder.Entity<RunEvent>().Property(x => x.Payload).HasColumnType("json");
        modelBuilder.Entity<ExpertRunAction>().Property(x => x.RequestJson).HasColumnType("json");
        modelBuilder.Entity<ExpertRunAction>().Property(x => x.Result).HasColumnType("json");
        modelBuilder.Entity<ActionExecutionAudit>().Property(x => x.Command).HasColumnType("json");
        modelBuilder.Entity<ActionExecutionAudit>().Property(x => x.Result).HasColumnType("json");
        modelBuilder.Entity<UserConnectorAuthorization>().Property(x => x.Scope).HasColumnType("json");
        modelBuilder.Entity<DeviceCapability>().Property(x => x.ValueSchema).HasColumnType("json");
        modelBuilder.Entity<DeviceState>().Property(x => x.State).HasColumnType("json");
        modelBuilder.Entity<SceneAction>().Property(x => x.TargetValue).HasColumnType("json");
        modelBuilder.Entity<SkillCatalog>().Property(x => x.InputSchema).HasColumnType("json");
        modelBuilder.Entity<SkillCatalog>().Property(x => x.OutputSchema).HasColumnType("json");
        modelBuilder.Entity<ScenarioTemplate>().Property(x => x.TriggerKeywords).HasColumnType("json");
        modelBuilder.Entity<ScenarioTemplate>().Property(x => x.Steps).HasColumnType("json");
        modelBuilder.Entity<ScenarioInstance>().Property(x => x.TriggerKeywords).HasColumnType("json");
        modelBuilder.Entity<ScenarioInstance>().Property(x => x.Steps).HasColumnType("json");
        modelBuilder.Entity<AutomationRule>().Property(x => x.TriggerConfig).HasColumnType("json");
        modelBuilder.Entity<AutomationRule>().Property(x => x.Conditions).HasColumnType("json");
        modelBuilder.Entity<AutomationRule>().Property(x => x.Actions).HasColumnType("json");
        modelBuilder.Entity<TeamRunTemplate>().Property(x => x.GraphJson).HasColumnType("json");
        modelBuilder.Entity<TeamRunTemplateVersion>().Property(x => x.MembersJson).HasColumnType("json");
        modelBuilder.Entity<TeamRunTemplateVersion>().Property(x => x.FileRefsJson).HasColumnType("json");
        modelBuilder.Entity<TeamRunTemplateVersion>().Property(x => x.PermissionIntersectionsJson).HasColumnType("json");
        modelBuilder.Entity<TeamRunTemplateVersion>().Property(x => x.GraphJson).HasColumnType("json");
        modelBuilder.Entity<TeamRun>().Property(x => x.SynthesisResultJson).HasColumnType("json");
        modelBuilder.Entity<TeamRunMember>().Property(x => x.PermissionIntersectionJson).HasColumnType("json");
        modelBuilder.Entity<TeamRunAudit>().Property(x => x.PayloadJson).HasColumnType("json");
        modelBuilder.Entity<FamilyMember>().Property(x => x.Preferences).HasColumnType("json");
        modelBuilder.Entity<FamilyMember>().Property(x => x.Birthday).HasColumnType("date");
        modelBuilder.Entity<FamilyKnowledge>().Property(x => x.ConfidenceScore).HasPrecision(4, 3);
        modelBuilder.Entity<DecisionHistory>().Property(x => x.Alternatives).HasColumnType("json");
        modelBuilder.Entity<FamilyAuditLog>().Property(x => x.BeforeJson).HasColumnType("json");
        modelBuilder.Entity<FamilyAuditLog>().Property(x => x.AfterJson).HasColumnType("json");
        modelBuilder.Entity<ConfirmationBatchRecord>().HasIndex(x => new { x.HomeId, x.IdempotencyKey }).IsUnique();
        modelBuilder.Entity<ConfirmationBatchRecord>().Property(x => x.ConfirmationIdsJson).HasColumnType("json");
        modelBuilder.Entity<ConfirmationBatchRecord>().Property(x => x.ResultJson).HasColumnType("json");
        modelBuilder.Entity<ConversationMessage>().HasIndex(x => new { x.ConversationId, x.RunId }).IsUnique();
        modelBuilder.Entity<ConversationMessage>().HasIndex(x => new { x.ConversationId, x.Id });
        modelBuilder.Entity<MemoryCandidate>().Property(x => x.Confidence).HasPrecision(4, 3);
        modelBuilder.Entity<MemoryCandidate>().Property(x => x.EvidenceRefsJson).HasColumnType("json");
        modelBuilder.Entity<MemoryReviewReceipt>().HasIndex(x => x.SourceRunId).IsUnique();
        modelBuilder.Entity<LearningMemoryRecord>().Property(x => x.Stability).HasPrecision(4, 3);
        modelBuilder.Entity<LearningMemoryRecord>().HasIndex(x => x.CandidateId).IsUnique();
        modelBuilder.Entity<LearningMemoryRecord>().HasIndex(x => new { x.HomeId, x.OwnerUserId, x.Status, x.LearnedAt });
    }

    private static void ConfigureStoreGeneratedTimestamps(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<User>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<UserIdentity>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<PasswordCredential>().Property(x => x.PasswordChangedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<AuthDevice>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<AuthRefreshToken>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<Tenant>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<Tenant>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<TenantMember>().Property(x => x.JoinedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<TenantMember>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<TenantMember>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<Todo>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<Todo>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<Subtask>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<Subtask>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<CalendarEvent>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<CalendarEvent>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<CalendarSubscription>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<CalendarSubscription>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<AiSkill>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<AiSkill>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<Expert>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<Expert>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<AgentRun>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<RunEvent>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<Conversation>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
        modelBuilder.Entity<Conversation>().Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate();
        modelBuilder.Entity<ConversationMessage>().Property(x => x.CreatedAt).ValueGeneratedOnAdd();
    }
}
