<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeMind.Common.Model\HomeMind.Common.Model.csproj" />
    <ProjectReference Include="..\HomeMind.Common.IRepository\HomeMind.Common.IRepository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />
  </ItemGroup>

</Project>
