<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeMind.Business.IServices\HomeMind.Business.IServices.csproj" />
    <ProjectReference Include="..\HomeMind.Common.Repository\HomeMind.Common.Repository.csproj" />
    <ProjectReference Include="..\HomeMind.Common.Infrastructure\HomeMind.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\HomeMind.Common.Helpers\HomeMind.Common.Helpers.csproj" />
    <ProjectReference Include="..\HomeMind.Common.Model\HomeMind.Common.Model.csproj" />
  </ItemGroup>

</Project>
